### ISSUE TITLE
Drop NodeJS < 8

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#101]
This will let us care less about polyfills.

For example, `String#padStart` is supported in all browsers, but in NodeJS only since v8.2.1+ http://node.green/#ES2017-features-String-padding.

As this is an experimental project, we shouldn't care about supporting older versions of Node / Racket / etc.
Once this project is no longer experimental, all the current versions will have become old.

**Comment by akshatgoel** [comment]
I think you make a valid point regarding RS being an experimental project. However, I think even in experiemental stage, we should support atleast 1 LTS for Node which I think is 6.11. Once Node announces new LTS support (I think release date is set in October 2017) and distros adopt that to be default installation, we can drop the support. @vishesh Thoughts?

**Comment by glebm** [comment]
> However, I think even in experiemental stage, we should support atleast 1 LTS for Node which I think is 6.11

Why is that?

**Comment by vishesh** [comment]
1. There are people who would like to try out RacketScript, and my understanding is that most of them are from Racket community, and many wouldn't care about latest NodeJS and would just use whatever is available from system package manager.
2. We are primarily targeting ES6 right now and Babel polyfill covers pretty much everything?
3. So far it didn't require extra effort to support older Node (or Racket). At this point I don't see strong enough reason to drop it, particularly if we can just rely on polyfill libraries on older versions. 
4. Regarding how far we want to go back in terms of version support, I think 1-1.5 years is fine. We don't have to strict about it, but it is good to keep it in check.

So unless it ends up being too much trouble and us being stuck, I would rather like to see some older versions around.

**Comment by glebm** [comment]
> 1. There are people who would like to try out RacketScript, and my understanding is that most of them are from Racket community, and many wouldn't care about latest NodeJS and would just use whatever is available from system package manager.

The current most popular Linux, Ubuntu, has node v4.2.6 in it latest LTS. We don't support that version of Node (few projects do anymore, it's EOL). Besides, we're invoking `node` which doesn't exist in Ubuntu (it's `nodejs`).

> 2. We are primarily targeting ES6 right now and Babel polyfill covers pretty much everything?
> 3. So far it didn't require extra effort to support older Node (or Racket). At this point I don't see strong enough reason to drop it, particularly if we can just rely on polyfill libraries on older versions.
> So unless it ends up being too much trouble and us being stuck, I would rather like to see some older versions around.

I'd like to completely remove babel/traceur/gulp/running npm from `racks`, and switch only to running TypeScript with a single parameter that is the target module system (the TypeScript compiler supports all the important ones).

We shouldn't have to worry about polyfills, now that we're using newer APIs.
In general, the compiler should not bundle any polyfills, nor prescribe a module system. This should be in control of and the responsibility of the user, like with any other node package out there.
 
> So unless it ends up being too much trouble and us being stuck, I would rather like to see some older versions around.

Yes I do believe doing this would take effort, and quite pointlessly so (see my first point about the distribution version of nodejs).

We should be treating the JavaScript runtime as the first class citizen in this codebase...

**Comment by vishesh** [comment]
> The current most popular Linux, Ubuntu, has node v4.2.6 in its latest LTS (16.04). We don't even support that version of Node (few new projects do anymore, it's in maintenance). Besides, we're invoking the node executable which doesn't exist in the Ubuntu version (there it's nodejs).

Wow! So did Ubuntu people stopped packaging NodeJS? Anyway, in that case we have an upcoming LTS for Node (8.something). I would be willing to take that as default one.

> I think it's very easy to install the latest version of any programming language, for anyone in the programming languages community is likely familiar with asdf.

That's not the point. Its easy to install latest version of things using certain tools, but lot of us just prefer to simply use the package manager when trying out some random software we just found on Github. Its kind of like Whalesong situation, where it does support older Racket but how many people actually go through the whole setting up multiple Racket thing? I personally, get annoyed when I have to work more than that. And that is why I like to make RS installation as smooth as possible.

On side note, for Whalesong Playground we got lots of students, and we may get those here as well (maybe we still do. We don't save the programs in RJS Playground server). In that context smooth installation is still something I would like to have. (`install.sh` can be useful there I think)

> In general, the compiler should not bundle any polyfills

I agree with that. My understanding is that we don't have to write any polyfills ourself but just install a dependency. On older version it would be used, on newer versions ignored. Or maybe something of that sort is doable?

> I'd like to completely remove babel/traceur/gulp/running npm from racks

I will talk about this in that patch later.

**Comment by glebm** [comment]
> Wow! So did Ubuntu people stopped packaging NodeJS?

No, they are still packaging it, it's just that most distributions are extremely conservative with versions and don't update the major version except when releasing a new major version of the distribution.
So the next LTS release of Ubuntu (18.04 LTS, April'18) will likely use the latest NodeJS LTS.

> Anyway, in that case we have an upcoming LTS for Node (8.something). I would be willing to take that as default one.

Done in #107 

> That's not the point. Its easy to install latest version of things using certain tools, but lot of us just prefer to simply use the package manager when trying out some random software we just found on Github.

Your system nodejs is installed as root. You're installing the global (`-g`) dependencies of some random software as root (unless you go through some configuration to install as user, but then you might as well not use the system nodejs). Don't do this, it will bite you eventually. Supporting this = supporting bad security practices.

The nodejs in the package manager is mostly for running other distribution packages written in nodejs (there is very few of these).

> smooth installation is still something I would like to have

Very achievable, especially for students. Even without using asdf and such, installing nodejs is a one-liner we can provide. Though I think we should still recommend asdf, especially for students, then our instructions can simply be:

---
The easiest way to install the latest version of Node.js and Racket on any distribution is:

1. [Install asdf](https://github.com/asdf-vm/asdf#setup). <-- one copy-paste.
2. Then, reload your shell and run: <-- and one more copy-paste.

   ```bash
   asdf plugin-add nodejs
   asdf plugin-add racket
   asdf install nodejs 8.4.0
   asdf global nodejs 8.4.0
   asdf install racket 6.10
   asdf global racket 6.10
   ```
---

> I agree with that. My understanding is that we don't have to write any polyfills ourself but just install a dependency. On older version it would be used, on newer versions ignored. Or maybe something of that sort is doable?

It's doable but we shouldn't be doing this! Polyfills, dead code elimination, etc, are not the responsibility of a tool that generates JavaScript. They are the responsibility of the bundling pipeline. You can of course provide a starter browser project template in a separate repository if you feel the need to make it very easy for someone unfamiliar with web technologies, but it shouldn't be built into the compiler.

**Comment by vishesh** [comment]
> . You can of course provide a starter browser project template in a separate repository if you feel the need to make it very easy for someone unfamiliar with web technologies, but it shouldn't be built into the compiler.

That's the idea until, and that's why I want to stick to whatever until we get some compiler driver improvements (the `raco` like driver task I talked about). I want this part of our pipeline for quick way to measure things  and that is why we have so many targets. At some point we may do our own DCE but that's not something that is concerning now.

**Comment by glebm** [comment]
What's DCE?

**Comment by vishesh** [comment]
Dead Code Elimination :)
