### ISSUE TITLE
Set up google/ts-style (clang-format + tslint) for all TypeScript code

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#104]
`clang-format` is great at formatting TypeScript.
We should add it (e.g. as `make tsfmt`) and always use it to eliminate discussions around code formatting.

**Comment by vishesh** [comment]
(y) if we use TypeScript. Does it support some style-guide? I used Airbnb whenever I can.

**Comment by glebm** [comment]
This is the Google clang-format + tslint configuration: https://github.com/google/ts-style
It takes care of 99% of what a style guide would be about.

For the remaining 1%, I'm not aware of one, but basically the Google JavaScript style guide could apply.

**Comment by glebm** [comment]
@vishesh By the way, don't know where else to post it, but check out this bookmarklet I made for showing code whitespace on GitHub.

https://gist.github.com/glebm/5b6c4517322193fbc51090dc3b57a44a

**Comment by vishesh** [comment]
Closing as we've added eslint. If `clang-format` can format plain JavaScript we can add that.
