### ISSUE TITLE
Help converting a function to RacketScript

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#109]
How would you convert this function to RacketScript?

```javascript
export function fprintf(out, form, ...args) {
    // TODO: Missing forms: ~.[asv], ~e, ~c.
    // TODO: The ~whitespace form should match Unicode whitespace.
    const regex = /~(?:[aAsSvVbBoOxX~n%]|\s+)/g;
    const formStr = form.toString();
    let reExecResult;
    let currentMatchIndex = 0;
    let prevIndex = 0;
    let lastMatch = '';
    while ((reExecResult = regex.exec(formStr)) !== null) {
        if (currentMatchIndex >= args.length) {
            throw Core.racketContractError('insufficient pattern arguments');
        }
        Core.display(out, formStr.slice(prevIndex + lastMatch.length, reExecResult.index));
        prevIndex = reExecResult.index;
        lastMatch = reExecResult[0];
        if (/^~\s/.test(lastMatch)) continue;
        switch (lastMatch.charAt[1]) {
            case '~':
                Core.display(out, '~');
                continue;
            case 'n':
            case '%':
                Core.display(out, '\n');
                continue;
        }
        const v = args[currentMatchIndex++];
        switch (lastMatch.charAt(1)) {
            case 'a':
            case 'A':
                Core.display(out, v);
                break;
            case 's':
            case 'S':
                Core.write(out, v);
                break;
            case 'v':
            case 'V':
                Core.print(out, v, Core.isPrintAsExpression(), 0);
                break;
            case 'b':
            case 'B':
                // TODO: raise exn:fail:contract if the number is not exact.
                Core.display(out, v.toString(2));
                break;
            case 'o':
            case 'O':
                // TODO: raise exn:fail:contract if the number is not exact.
                Core.display(out, v.toString(8));
                break;
            case 'x':
            case 'X':
                // TODO: raise exn:fail:contract if the number is not exact.
                Core.display(out, v.toString(16));
                break;
            default:
                throw racketContractError('Unsupported format:', lastMatch);
        }
    }
    if (lastMatch.length + prevIndex < form.length) {
        Core.display(out, formStr.slice(lastMatch.length + prevIndex));
    }
}
```

@vishesh I'm trying to see if it's viable, as you mention in several comments in various issues, but I don't know enough RacketScript and there is little documentation :|

We want this function to be fast so the RacketScript version should ideally produce the same JavaScript (no extra function calls).

**Comment by vishesh** [comment]
What problems are you facing?

- Compiler can translate the tail call recursion to `while` loops. So there is no loop as recursion overhead involved here.
- `case` in Racket is a macro which expands to if/else. We can't lift it back to`switch` statements, but that's a compiler enhancement. I need that for my work around `yield`, `async/await` stuff too. 

Overall, if you think something is slow because compiler doesn't produce good enough code or can't be expressed, its a compiler/ffi/`#lang racketscript/boot` bug and using JavaScript is not the answer.

1. If we didn't use RacketScript we wouldn't know what's wrong at first place.
2. If we use JavaScript because it is faster, we'll have slightly less motivation (procrastination) to work on getting the enhancement into compiler, not to mention rewrite the whole thing again when we can get the enhancement in.

**Comment by glebm** [comment]
Sorry I should've made a list. Here is a list of things I don't know how to do. Just edit my comment to reply

* Spread ...args

  ```javascript
  function fprintf(out, form, ...args)
  ```
  ```racket
  
  ```

* Native RegExp

  ```js
  /~(?:[aAsSvVbBoOxX~n%]|\s+)/g
  ```

  ```racket
  
  ```

* Native switch / case:
  
  ```js
  switch (lastMatch.charAt(1)) {
      case 'a':
      case 'A':
          stuff();
          break;
     default: otherStuff();
  }
  ```

  TODO: Tracking issue with proposed syntax?

  ```racket
  
  ```

* `const` and `let` variables.

  ```js
  const a = 1;
  let b;
  let c = 2;
  ```

  ```racket
  
  ```

**Comment by glebm** [comment]
> not to mention rewrite the whole thing again when we can get the enhancement in.

If an optimization is missing, sure. But if the syntax is missing, it's a rewrite either way, and having it in JavaScript will at least tell us the expectation of the RacketScript version.

**Comment by vishesh** [comment]
> Spread args

Used throughout kernel.

https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/compiler/runtime/kernel.rkt#L200

> Native RegExp

Try RacketScript regexp which uses native regexp. We can add a FFI to directly put in regexp literals if necessary. Right now let us try to use whatever we have from core.

> Native switch / case:

I didn't create an issue, but I wont add a FFI to directly create this, but rather prefer compiler optimization do it whenever you can. From a programmer/stdlib perspective, it shouldn't matter how it happens or if there is internal representation or special case.

> cons and let

You don't need `let`. Racket already has proper lexical scoping, and RacketScript preserve those semantics. Racket doesn't have `const` so there is no need to do same for JS.
