### ISSUE TITLE
Use `WeakMap` for continuation mark frames and parameterization

### ISSUE THREAD

**Issue by vishesh** [vishesh/racketscript#117]
There doesn't seem to extract keys from `current-continuation-marks`. `w-c-m` keys are compared using `eq?` as it seems from following example below:

```racket
(with-continuation-mark (posn 1 2) 'value
  (extract-current-continuation-marks (posn 1 2)))
;;=> '()

(let ([p (posn 1 2)])
  (with-continuation-mark p 'value
    (extract-current-continuation-marks p)))
;;=> '(value)

(with-continuation-mark '(1 2) 'value
  (extract-current-continuation-marks '(1 2)))
;;=> '()

(with-continuation-mark 'key 'value
  (extract-current-continuation-marks
   (string->uninterned-symbol "key")))
;;=> '()
```
 We internally use a native dictionary and use hashing (hasheq so we don't actually get collisions at-least) to keep key-value pairs. With our recent discussion around WeakMap, it occurred to me that maybe we should have used `WeakMap` here as we can never get a key unless we already know what it is. (https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/compiler/runtime/core/marks.js#L129). If I'm not mistaken here, it should be easy fix.

This next brings us to parameterization. In here we use HAMT which avoid linear lookup and persistence. However, parameters are also supposed to be GCed, and in our case would be held backed by our parameterization representation. So unless we get immutable WeakMap, we have to use a new WeakMap for each frame, and ref operation will go through each of them in-order. All that said, parameters I think are top-level bound hence should live for life. With DCE  in future we can potentially remove unused parameters  as well. With that said I think it is ok to not worry about GC issue in case of parameters? Thoughts?

**Comment by stchang** [comment]
`WeakMap` only allows object keys though. Wouldnt that be a problem?

And I think it's fine to not worry about gc'ing of parameters. Parameters are typically associated with threads so it's already not the same as Racket.

**Comment by vishesh** [comment]
> WeakMap only allows object keys though. Wouldnt that be a problem?

Right now we just have numbers left that are actually JS primitive. The other option with small overhead would be to use object for numbers and WeakMap for everything else. This way we can allow foreign primitives to be in continuation frame. Not sure if its actually useful, but sounds like easy change.

But now I'm thinking, that key can either be bound lexically or passed directly to w-c-m. In first case w-c-m will always be in body of that `let-values` which means the key wont be gc'ed at first place before WCM ends. If passed directly, we'll delete that frame as soon as we get out of that WCM and key will be eventually gc'ed. And it hardly make sense to set marks if you are never going to use it.

So I think this is probably a false alarm. :D

> Parameters are typically associated with threads so it's already not the same as Racket.

Cool! Good reminder.

**Comment by stchang** [comment]
Ok great.
