### ISSUE TITLE
Repo branches

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#119]
GitHub thinks the development happens on `master`, as it is currently set as the default branch in the repo's GitHub settings.

How about we set `develop` as the default GitHub branch?

Or, alternatively, make `master` the development branch and have a `stable` (or `release`) branch for releases?

**Comment by vishesh** [comment]
My workflow is roughly like this[0].

My rationale was that I made lots of quick changes with potential of breaking things. I didn't expect first timers to actually go through README that some non-default branch is stable branch when installing RS, and wasn't concerned with Github activity stuff.

Merging develop into master was more frequent in past as we anyway were less stable and less visible. The third option is to make a more frequent schedule for merging things (a month? biweekly?).

@stchang Any thoughts?

[0] http://nvie.com/posts/a-successful-git-branching-model/

**Comment by glebm** [comment]
@vishesh How about a GitHub Pages site with the README from the current release for newcomers?

**Comment by vishesh** [comment]
@glebm Didn't get you point. The instructions can be in the README itself to warn master is the active development branch.

I'm in general ok to have one branch for master and develop. The only reason I've avoided so far is that we don't have a way to produce coverage report and unit-tests for JS runtime #18 , which makes me less confident about stability. `fixtures.rkt` is the only way we test that.

If we can be confident about keeping default branch stable with proper coverage report and unit-tests there is no reason I can think of to have just one branch with just tags for releases.

**Comment by glebm** [comment]
Having one branch works even better, once there is HAS coverage, yeah.

With two branches, the default should be the development one.

I had thought there was a different reason why you have the stable branch as the default. E.g. I had a lot of people getting confused with having the development branch as the default (even with a warning), but that was in a very popular repo with lots of inexperienced developers among the users. Nevertheless, now all my repos have a homepage that's not the GitHub repo home.

**Comment by vishesh** [comment]
So for lack of #18, I'm closing this for now.
