### ISSUE TITLE
Use ...spread arguments instead of `arguments`

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#129]
This is faster, will work with arrow functions (they do not bind the `arguments` object), and will allow us to compile to regular function calls instead of `fn.apply`.

**Comment by vishesh** [comment]
Can you point parts of code in description?

I like the idea of using "..." in lambdas, however last year Babel would compile it down to a for loop copying each argument to an array.

**Comment by glebm** [comment]
What babel compiles it to only depends on what you set the Babel's language target to.

> Can you point parts of code in description?

I'm guessing it's things like `apply`, `call-with-values`, and variadic arguments.

**Comment by glebm** [comment]
@vishesh Updated the comment above with some details on how this would make `apply` and `call-with-values` simpler (and faster).

**Comment by glebm** [comment]
If we do this, I think we may even be able to remove the `Values` class.

**Comment by vishesh** [comment]
Ok I guess browsers/node support these now. Seems like we definitely can do this in future. From compiler perspective, I don't think we'll have much trouble, except maybe for application. I can give it a go with the work I'm trying to pull off with our identifier problem.

I also like the idea of making list an iterator.

How fast are they? Any sources?

**Comment by vishesh** [comment]
And `define-values` to

```
(define-values (a b c) (values 1 2 3))

;;=> let [a, b, c] = [1, 2, 3]
;;=> let [a, b, c] = xx // also valid

```

Overall sounds good.

**Comment by glebm** [comment]
> How fast are they? Any sources?

* Much faster than iterating over `arguments`.
* Faster than calling `fn.apply` if you have an iterable. https://jsperf.com/apply-vs-spread-with-iterable
* Slower than calling `fn.apply` if you have an array, even if it comes from another spread. https://jsperf.com/apply-vs-spread-with-spread

Interestingly, looks like in Chrome 62 Canary the spread is no longer slower than `apply` even in the array case. My guess is it can be optimized even further as it has much simpler semantics than `apply` (no `this` re-binding etc).

**Comment by vishesh** [comment]
That's a good start and looks promising. I would do that just to avoid the `this` binding weirdness. However, it would be interesting see how real workload pans out, as micro-benchmarks can sometimes be misleading because of JIT and easy pattern recognition.
