### ISSUE TITLE
IRC or Slack

### ISSUE THREAD

**Issue by vishesh** [vishesh/racketscript#130]
The activity here has increased quite a bit (yay!). Github messages are nice, but I think we should also have a IRC or Slack channel. Let me know what you guys prefer. I will hangout there:

1. IRC: I've created a channel named #racketscript.
2. Slack: Maybe we can ask Racket, if we can create a #racketscript channel there.

**Comment by glebm** [comment]
Gitter

**Comment by vishesh** [comment]
Gitter looks really cool. The reason I proposed Slack and IRC was because almost all Racket community hangs out at these two places, and for Slack we can potentially create a channel in existing Racket account and stay close to the community. If instead we have to create a new Slack account, we definitely can try Gitter. If everyone idles 24x7 at IRC it is least distracting option.

**Comment by jackfirth** [comment]
As someone who regularly uses the racket slack and is very interested in racketscript, I would really like to be able to follow racketscript's development in a slack channel. But I'm merely an observer, not a contributor.

**Comment by vishesh** [comment]
Its good idea to stay on Slack to be around Racket. All of us seem to have Slack already, so no extra app needed. I've created a Slack channel #racketscript at https://racket.slack.com. Thanks!
