### ISSUE TITLE
v0.4-alpha breaks methods that start with non-alpha chars

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#133]
Particularly, all number comparison methods.

These are the method names at definition-site:

```javascript
__by_
__eq_
__gt_
__gt__eq_
__lt_
__lt__eq_
__plus_
__times_
```

At call site:

```racket
(= 3 (vector-length v))
```

they are compiled to:

```javascript
M2._eq_(3, M2.vector_length(v1825)) !== false
```

Note the single vs double leading underscore

**Comment by vishesh** [comment]
Did you try to do a force recompile? `racks -r /path/to/foo.rkt`?

**Comment by glebm** [comment]
Yes, that was the issue. I did change the file, but that was not sufficient, as it didn't recompile the runtime.

**Comment by vishesh** [comment]
Yeah. That's a known issue. There are other subtleties #131
