### ISSUE TITLE
"raco pkg install racketscript" Does Not Install 'racks' Binary

### ISSUE THREAD

**Issue by 7enderhead** [vishesh/racketscript#136]
The compiler itself is nowhere to be found after package installation.

**Comment by vishesh** [comment]
Hi @7enderhead, can you give some details on platform/Racket version you are using?

**Comment by glebm** [comment]
The `racks` binary is installed to:

```
racket -e "(require setup/dirs) (display (find-user-console-bin-dir))"
```

You can either add that directory to your `PATH`, or create a shim `racks` executable in your PATH:

```bash
#!/bin/bash

"$(racket -e "(require setup/dirs) (display (find-user-console-bin-dir))")/racks" "$@"
```

**Comment by 7enderhead** [comment]
Racket 6.10.1 on Linux Mint 17.1

**Comment by 7enderhead** [comment]
@glebm: Okay, there it is. Perhaps you could put that into the documentation.

**Comment by glebm** [comment]
I had put it in the documentation but @vishesh removed it.

**Comment by vishesh** [comment]
We use the `raco` infrastructure like every other Racket package to put executable in PATH, so I do not think it should go directly into README. I've made a [wiki page](https://github.com/vishesh/racketscript/wiki/Troubleshooting) instead (there is link in README too) where we can list any common problems faced by new users.
