### ISSUE TITLE
Readme: Link to Racketscript playground is dead

### ISSUE THREAD

**Issue by knbknb** [vishesh/racketscript#138]
The server [RacketScript Playground](http://rapture.twistedplane.com:8080/) seems to be offline. (I've just tried it once, so this can also be a transient issue).

Please update the link, or add a note that the server is unreachable sometimes. This would make the README file more user-friendly.

I came here from the Page [List of languages that compile to JS](https://github.com/jashkenas/coffeescript/wiki/list-of-languages-that-compile-to-js), and most of the projects in the list-section "Scheme-like" languages have been abandoned or evolved into another one on that list. 
This project (racketscript) seems to be different. Eager to try it out without installing a whole lot of stuff.

**Comment by vishesh** [comment]
Hi, thanks for trying RackeScript. The link is still same. I was making some changes to server and something went wrong. The server back up, but something is still broken. I will get back on this later.

**Comment by vishesh** [comment]
Playground is backup.
