### ISSUE TITLE
Webassembly?

### ISSUE THREAD

**Issue by spdegabrielle** [vishesh/racketscript#139]
Can racketscript compile to webassembly?

http://webassembly.org 
http://webassembly.org/getting-started/developers-guide/

**Comment by vishesh** [comment]
Hi Stephen,

Not right now, and no immediate plans to do so. But never say never. I think we should wait until we know how GC support will pan out in WebAssembly.

https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md
https://github.com/WebAssembly/design/issues/1079

**Comment by spdegabrielle** [comment]
thanks
