### ISSUE TITLE
racks --target traceur-browser omits link to jquery

### ISSUE THREAD

**Issue by danprager** [vishesh/racketscript#142]
To get the colored-carpet.rkt example to work I had to manually insert an additional line in the generated index.html:

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

**Comment by vishesh** [comment]
Thanks for reporting. I will close this for now without fix as we do not depend on jquery, and I'm planning to improve project build in #131 which should subsume this.

Your feedback is welcome on how end result should be like.
