### ISSUE TITLE
RacketScript broken for Racket 7

### ISSUE THREAD

**Issue by vishesh** [vishesh/racketscript#143]
Seems like some new modules and some things moved from `#%kernel` to `#%runtime`.

```
± % traceur js-build/modules/fact.rkt.js
Error: Error: ENOENT: no such file or directory, open '/home/vishesh/Racket/racketscript/tests/js-build/collects/racket/private/misc.rkt.js'
Specified as ../collects/racket/private/misc.rkt.js.
Imported by /home/vishesh/Racket/racketscript/tests/js-build/modules/fact.rkt.js.
Normalizes to /home/vishesh/Racket/racketscript/tests/js-build/collects/racket/private/misc.rkt.js
locate resolved against base '/home/vishesh/Racket/racketscript/tests/'

    at InternalLoader.handleCodeUnitLoadError (/home/vishesh/.nvm/versions/node/v10.10.0/lib/node_modules/traceur/bin/traceur.js:33360:40)
    at /home/vishesh/.nvm/versions/node/v10.10.0/lib/node_modules/traceur/bin/traceur.js:33222:20

```

**Comment by brown131** [comment]
Is a fix forthcoming?

**Comment by vishesh** [comment]
I'm not actively working in this fix at the moment. I think I will probably start work after couple of weeks. If you are interested I can share a WIP patch meanwhile.

Also, with a fix for this, I will drop support for 6.x. Racket 7 comes with bunch of changes including linklets, and wouldn't want to make things harder by supporting 6.x.

**Comment by brown131** [comment]
Thanks for your answer! After trying to use GHCJS, I was afraid that this project was rusting as well. 

I'm all in favor of you fixing forward and focusing your energies on 7.0.

**Comment by gregid** [comment]
Is there any update on the upgrade to Racket 7.0?

**Comment by juszczakn** [comment]
I took a stab at this.

https://github.com/juszczakn/racketscript/commit/e200be0ea39aa058ee1d2db2b933eab196ed4059

It's kinda a hack, to get started. 

The next problem seems to bet that #%kernel isn't getting listed as a import for something. Not sure what or how that's happening. 

I was able to actually finish a compile on latest racket 7.2 by adding:
```
modified   racketscript-compiler/racketscript/compiler/expand.rkt
@@ -365,7 +365,7 @@
     #:literal-sets ((kernel-literals #:phase (current-phase)))
     [(module name:id lang:expr (#%plain-module-begin forms ...))
      (parameterize ([current-module path]
-                    [current-module-imports (set)]
+                    [current-module-imports (set '#%kernel)]    ;;<----
                     [current-directory (path-only path)]
                     [lexical-bindings (make-free-id-table)])
        (define mod-id (syntax-e #'name))
```
Which I think is just basically making is so that everything implicitly includes kernel as an import, which is obviously not correct, and caused some cyclic dependencies in the output js that traceur couldn't handle.

Additionally, the gulpfile that is generated is incorrect now, because as of gulp 4.0 they changed the task syntax, so that'll need to be updated (or an older version of gulp specified in the build).

So yea, I think I could get a "build" to happen, just not correctly.

**Comment by vishesh** [comment]
Apologies for delaying for this long. I've currently a fix[1] which fixes most of this build (I only see `racket-core/list.rkt`  and `parameter-set.rkt` test failing apart from some defunct unit tests in `expand.rkt`).

@juszczakn  Thank you very much for looking into this. For now I've set the Gulp version to old one so that we can focus on getting Racket 7 stuff working. That said, we probably should rethink about keeping Gulp in our build. I don't ever liking the decision of adding another extra dependency  of Gulp, but it was convenient. I would more than gladly take any suggestions/alternatives, or fixes to upgrade to latest Gulp.

[1] https://github.com/vishesh/racketscript/tree/task/issue-143

**Comment by juszczakn** [comment]
Cool, I'll see about taking another look this weekend at it.

**Comment by shriram** [comment]
Hi — any updates? I just ran into this problem. @juszczakn were you able to confirm this?

**Comment by juszczakn** [comment]
I tried out the issue-143 branch, but didn't have any luck with it. Seems like there's still some work to go on it.

**Comment by stchang** [comment]
I submitted #148 that is a first stab at fixing the tests for Racket7. Feedback welcome.

**Comment by stchang** [comment]
Tests, when run with Racket 7.x, fixed in https://github.com/vishesh/racketscript/commit/2d6dae8b2e6f57aace1e046242ad9765b9687334

So closing this for now.
