### ISSUE TITLE
string cmp fns, eg string<? sometimes return wrong result

### ISSUE THREAD

**Issue by stchang** [vishesh/racketscript#149]
eg
`(string<? "b" "aa")` should be `#f` but returns `#t`

**Comment by vishesh** [comment]
This condition: https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/compiler/runtime/core/unicode_string.js#L437 :(

**Comment by stchang** [comment]
Yeah I saw it too. I'm fixing it.

**Comment by stchang** [comment]
It also crashes when second arg is substring of first arg.

**Comment by vishesh** [comment]
Seems like we will need many more tests for `strings` in general.  Are you trying to port the Racket's string tests?

**Comment by stchang** [comment]
I'm porting some of Racket's hash tests right now.

In the bigger picture I'm trying to make RacketScript self-hosted, with the first step being to compile [the expander code](https://github.com/racket/racket/tree/master/racket/src/expander), ie the `expand` function. If you're interested and you have time, feel free to pick any random module and get it to compile. :) (I'm working on the sets implementation right now.)
