### ISSUE TITLE
procedure variable arity?

### ISSUE THREAD

**Issue by stchang** [vishesh/racketscript#153]
I'm currently trying to improve error handling to better match racket and that involves implementing `procedure-arity-includes?` which gets called a lot.

One thing I ran into is that I think it's currently not possible to identify variable arity functions. Is that right?

Can we do this by adding another field, similar to [`__rjs_arityValue` here](https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/compiler/runtime/core/procedure.js)?

**Comment by vishesh** [comment]
It works IMO right now, but there seems to be a bug.

```racket
#lang racket

(equal? (procedure-arity (lambda (x) x)) 1)
;;> #t

(displayln (procedure-arity (lambda (x . y) x)))
;;> #(struct:kernel:arity-at-least 1)

(equal? (procedure-arity (lambda (x . y) x) (arity-at-least 1)))
;;> #f  -- WRONG: should be #t
```
The `arity-at-least` is computed correctly. IIRC looking at definition of[ `procedure-arity`](https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/compiler/runtime/kernel.rkt#L1033) the valu of `__rjs_arityValue` is supposed to be an array when its variable.

One problem however I see is in the last case of above example. Somehow, `arity-at-least` is not equal to `kernel:arity-at-least`.

**Comment by stchang** [comment]
oh i see. what about primitives like `values` or `list`? calling `procedure-arity` returns the result of the `length` field, which is 0.

would calling `attachProcedureArity` around the definition fix this?

**Comment by vishesh** [comment]
Yes, I think any `lambda` with variable arity should be wrapped with `attachProcedureArity`. Missed doing that for kernel primitives.

Currently almost all kernel primitive use `define+provide` so should be an easy fix. We can perhaps introduce `define-kernel-primitive` or something so that any internal define doesn't have that overhead?
