### ISSUE TITLE
`racks` not found

### ISSUE THREAD

**Issue by srfoster** [vishesh/racketscript#162]
I tried the first two installation methods on the README.  The `racks` command is unrecognized, though.

Ubuntu 19.10, Racket 7.5, node 10.15.2.

No error messages.

**Comment by vishesh** [comment]
`racks` should be installed on `$HOME/.racket/$RACKET_VERSION/` (e.g. in my case its `~/.racket/7.0/bin/`). Do you see it installed in that directory? IIUC that directory should be added by default to `$PATH`.

**Comment by srfoster** [comment]
Thanks!   l looked there, and I do have the file.  It just wasn't on my `$PATH`.
