### ISSUE TITLE
Error when compiling simple file

### ISSUE THREAD

**Issue by Karrq** [vishesh/racketscript#166]
Hello! I made a simple racket script to encrypt and decrypt something before sending it to a remote server and I was trying to compile to javascript using racketscript so I wouldn't need a racket installation on other systems to run it.

Unfortunately I ran into an error while compiling it.
Here's racks' [stdout](http://ix.io/2hIx) and [stderr](http://ix.io/2hIs).

Here's my [script](http://ix.io/2hIy/racket)

**Comment by stchang** [comment]
Hi. The issue it that racketscript does not support complex numbers yet. See https://github.com/vishesh/racketscript/issues/93

**Comment by Karrq** [comment]
Hi, thank you for your reply, but I am not aware of using complex numbers in my script. Can you show me or tell me how you reached the conclusion that I'm using complex numbers in my script and where ?

**Comment by stchang** [comment]
Oh sorry. I guessed it from the supplied [stderr](http://ix.io/2hIs) msg, which says `unsupported value0+0.0i`. It could also be from one of the libraries like `crypto`?

**Comment by vishesh** [comment]
Also, I think `crypto` is written as a FFI wrapper over some well known C crypto library.

**Comment by Karrq** [comment]
So is FFI not supported by racketscript?
I didn't see anything specified anywhere about that so I assumed it was supported...

I guess I will have to rewrite this somehow or just write it in javascript directly unfortunately

**Comment by vishesh** [comment]
As in the Racket C FFI wont work in NodeJS. The `crypto` library seems to allow different crypto providers, so maybe it is possible to use RacketScript FFI to implement one of those provider for NodeJS crypto.

**Comment by Karrq** [comment]
I don't even know what RacketScript FFI is or how to go ahead and implement this...
