### ISSUE TITLE
github.com/racketscript github organisation ?

### ISSUE THREAD

**Issue by spdegabrielle** [vishesh/racketscript#172]
Hi @stchang  

Just noticed https://github.com/racketscript github organisation

is this you or @vishesh ? or perhaps someone else?

**Comment by vishesh** [comment]
Yes, it is us. I created the org long time ago, and forgot about moving there as I've not been active.

**Comment by spdegabrielle** [comment]
Sorry I should have responded sooner.

I'm looking at ways to attract contributors to this project.

I think this will be easier once it is back in working order - @stchang has a plan for this as an outcome of a discussion with MatthiasF. (My understanding is introducing 'linklets' was  the breaking change.)

I believe we also have a commitment from MF to add RacketScript to the Racket organisation on GitHub once it is working - to give it the standing it deserves.

Thank you for you creating RacketScript!
