### ISSUE TITLE
Create a roadmap for RacketScript

### ISSUE THREAD

**Issue by daynin** [vishesh/racketscript#186]
@vishesh

First of all! Thank you for a great project!

I wanted to suggest creating some kind of a roadmap just to address important things to do.

What I can find useful from my perspective right now:
1. Fixing all eslint issues (almost done https://github.com/vishesh/racketscript/pull/185). It allows us to avoid occasional issues in the future. Because right now it's hard to find a new issue among hundreds of old ones.
2. Add real types for TS or delete TS-check because now it can't say us something important (there are tons of false-negative errors). We can't really type check type unsounded code right now.
3. Upgrade parental platforms: Node.js to LTS version and Racket to Racket 8. Now some tests fail on Racket 8.
4. Find and delete dead code (I found a few places with dead code while fixing eslint issues).
5. Add documentation.
6. Extract TODOs from code and create issues instead.

**Comment by stchang** [comment]
Thanks for starting this, and for updating the eslint config. Some tools in the setup have indeed fallen a little out of date.

But it's on my immediate list of things to do to update everything (likely later next week), particularly getting Racket 8 working.

If you've already started looking into things, definitely feel free to open more issue tickets, even if it's just to report which tests fail or other preliminary things.

Thanks again!

**Comment by daynin** [comment]
I think we already have done a part of the tasks from the list. I'll add the rest of the list as separate issues. This issue can be closed.
