### ISSUE TITLE
Stop supporting Racket 6.9

### ISSUE THREAD

**Issue by daynin** [vishesh/racketscript#192]
Now tests don't pass on Racket 6.9. Looks like it's better to stop supporting this version because of 3 important reasons:
1. Racket 6.9 was released 4 years ago.
2. It will be hard enough to support a huge variety of versions and looks like it's easier to stop supporting Racket 6.9 than fix all failed tests.
3. RacketScript now doesn't have a lot of users (maybe I'm wrong here), so it's better to avoid creating legacy code at the very beginning of the project.

What do you think?

**Comment by stchang** [comment]
Yes, agree completely

**Comment by daynin** [comment]
done here https://github.com/vishesh/racketscript/pull/194
