### ISSUE TITLE
big-bang loop out of sync?

### ISSUE THREAD

**Issue by stchang** [vishesh/racketscript#216]
Sorry in advance for this vague issue. Trying to revive the big-bang examples and, not completely sure, but they seem to error because this loop falls through: https://github.com/vishesh/racketscript/blob/master/racketscript-extras/racketscript/htdp/universe.rkt#L143-L159 i.e., there are no events and `world-changed = #f`. Should that ever happen?

I think it might be because the timeouts here are out of sync, ie they happen too slow: https://github.com/vishesh/racketscript/blob/master/racketscript-extras/racketscript/htdp/universe.rkt#L204-L207 . Could that be the case? But I tried tinkering with the rate and it didnt help.

Not sure what's changed since it was last working, but with modern js, should we use `await` somewhere?

**Comment by vishesh** [comment]
Didn't quite get the issue. I finally managed to compile few examples myself  (falling sky, tetris and flappy birds) and seemed alright. Maybe we can do a quick video call and see what's going on here (and also maybe plan anything else that needs done)?

Also, check https://github.com/vishesh/racketscript/issues/217. Did you compile big-bang with arity-checks or without them? If you fixed the arity issue, maybe that's somehow slowed things down?

**Comment by stchang** [comment]
Ah, `--skip-arity-checks` fixed my problem. Thanks.
