### ISSUE TITLE
The racketscript playground is down

### ISSUE THREAD

**Issue by samfrances** [vishesh/racketscript#232]
Looks like the server is down.

**Comment by vishesh** [comment]
@stchang : Can I start the current published build on port 80? You can pull your dev builds with different tag and run on other port?

**Comment by vishesh** [comment]
Also, I was trying to run a build on [Heroku](https://racketscript-playground.herokuapp.com) a while ago (as its free, so why not), and was getting following error for same image. Since you worked on some path stuff recently, do you recall seeing anything like this?

```racket
Compilation error:
standard-module-name-resolver: collection not found
  for module path: (lib "racketscript/compiler/main.rkt")
  collection: "racketscript/compiler"
  in collection directories:
   /root/racketscript-playground/.local/share/racket/8.1/collects
   /usr/share/racket/collects/
   ... [164 additional linked and package directories]
```

**Comment by stchang** [comment]
I'm fixing this now. (Sorry playground was in debug mode)

**Comment by stchang** [comment]
It's back up and running again
