### ISSUE TITLE
`eval` does not work

### ISSUE THREAD

**Issue by shriram** [vishesh/racketscript#32]
"TypeError: M0.eval is not a function"

**Comment by vishesh** [comment]
We still use Racket's reader and expander so its unlikely that will happen.

**Comment by shriram** [comment]
Why doesn't it at least statically reject functions that have not been implemented?

**Comment by stchang** [comment]
It's because we are in the process of transitioning the kernel implementation but yes this is unacceptable. Closing the original issue since we currently have no plans to implement a javascript expander.
