### ISSUE TITLE
`big-bang` (maybe `text`) does not display values properly

### ISSUE THREAD

**Issue by shriram** [vishesh/racketscript#33]
```
#lang racketscript/base

(require racketscript/htdp/image
         racketscript/htdp/universe
)

(define (tick1 n)
  (add1 n))

(define (show1 n)
  (text (number->string n) 50 "blue"))

(define (show2 n)
  (text (string-append " " (number->string n) " ") 50 "blue"))

(define a
  (big-bang 0
            [on-tick tick1]
            [to-draw show1]
            [stop-when (lambda (n) (> n 100))]))
```

This should show the values from 1 to 100. But when the numbers go into double-digits, it has trouble showing everything past the first digit properly.

Note that if I use `show2` instead it does a _bit_ better: the second digit is partially visible. Here, e.g, is where it ends (this is "100"):

![image](https://cloud.githubusercontent.com/assets/75030/21314003/be7e15e2-c5c2-11e6-93b5-ad6ede78e548.png)

**Comment by stchang** [comment]
Thanks, I was going to file this one too. I had to use `empty-scene` to get things to show properly.

**Comment by vishesh** [comment]
It is actually expected behavior. The documentation for [to-draw](https://docs.racket-lang.org/teachpack/2htdpuniverse.html#%28form._world._%28%28lib._2htdp%2Funiverse..rkt%29._to-draw%29%29) says that the size of canvas is determined by the image of first world.

**Comment by stchang** [comment]
Ok good, so using `empty-scene` is appropriate and expected.
