### ISSUE TITLE
How to upgrade?

### ISSUE THREAD

**Issue by bentxt** [vishesh/racketscript#53]
What's the best way to upgrade the 'racketscript' installation?

**Comment by vishesh** [comment]
If you are using the Racket package manager `raco`, try the [raco update](https://docs.racket-lang.org/pkg/cmdline.html#%28part._raco-pkg-update%29) command.

Otherwise, just doing a git pull on master branch followed by `make` command should suffice.

**Comment by bentxt** [comment]
ok, thanks
