### ISSUE TITLE
error with 'make integration-test': tests/fixture.rkt:5:9: collection not found

### ISSUE THREAD

**Issue by ghost** [vishesh/racketscript#55]
RACKETSCRIPT INTEGRATION TEST    
racket --version
Welcome to Racket v6.9.

racketscript version:
> git describe --tags
v0.2-alpha-4-g3d221e2
> git rev-parse HEAD
3d221e2284f1312fdc38d50be7b4bb462c23024e

>make integration-test
++++++++++++++++++++++++++++++++
raco test -t tests/fixture.rkt
tests/fixture.rkt:5:9: collection not found
  for module path: glob
  collection: "glob"
  in collection directories:
   /home/bkb/.racket/6.9/collects
   /usr/local/share/racket/collects
   ... [175 additional linked and package directories]
  context...:
   show-collection-err
   standard-module-name-resolver
   [repeats 1 more time]
   /usr/local/share/racket/pkgs/compiler-lib/compiler/commands/test.rkt:550:0: test-files79
   /usr/local/share/racket/pkgs/compiler-lib/compiler/commands/test.rkt:433:0: map/parallel49
   ...cket/cmdline.rkt:179:51
   /usr/local/share/racket/pkgs/compiler-lib/compiler/commands/test.rkt: [running body]
   /usr/local/share/racket/collects/raco/raco.rkt: [running body]
   /usr/local/share/racket/collects/raco/main.rkt: [running body]
Makefile:75: recipe for target 'integration-test' failed
make: *** [integration-test] Error 1

**Comment by vishesh** [comment]
You should run `make setup-extra` if you are trying to run integration test or coverage. Its documented in [HACKING](https://github.com/vishesh/racketscript#hacking). Hope that resolves the issue.

**Comment by vishesh** [comment]
Please re-open if issue still exist.
