### ISSUE TITLE
Error(compile):Cannot find module './lib/runTask'

### ISSUE THREAD

**Issue by ghost** [vishesh/racketscript#57]
I have a new error when compiling with babel:

> racks --target babel  tests/basic/fact.rkt

Error:

npm WARN racketscript@0.0.1 No license field.
module.js:328
    throw err;
    ^

Error: Cannot find module './lib/runTask'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/...racketscript/js-build/node_modules/orchestrator/index.js:8:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
[info] Finished.

**Comment by vishesh** [comment]
Can you share your Racket/Node/NPM/Gulp versions? This seems to be some Gulp related issue.

**Comment by bentxt** [comment]
$ racket --version
Welcome to Racket v6.9.

$ node --version
v4.2.6

$ npm --version
3.5.2

$ gulp --version
[13:40:07] CLI version 3.9.1


$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

**Comment by vishesh** [comment]
It seems like a Node 4.x specific issue. Adding `babel-runtime` and `babel-core` to dependencies in `js-build/package.json` fixes issues for me. Can you please confirm this?

I use Node 6.9.1 by default on my dev machine where this is non-issue.

**Comment by vishesh** [comment]
Please re-open if you still stumble on this.

**Comment by leodak** [comment]
I have same issue

**Comment by leodak** [comment]
Could you please shed your ideas? my node version is 8.15 and gulp is 3.9.1

**Comment by vishesh** [comment]
@leodak : Seems like build is broken too. By any chance the error you are facing is https://travis-ci.org/vishesh/racketscript/jobs/494053805#L927 instead of current issue?

**Comment by stus3y** [comment]
I have the same issue

**Comment by vishesh** [comment]
I think recent version should fix it.
