### ISSUE TITLE
Invalid JavaScript generated when Racket identifier begins with a decimal digit

### ISSUE THREAD

**Issue by arjunguha** [vishesh/racketscript#63]
(Verified on RacketScript Playground and using the current version of RacketScript on raco.)

This program:

```
#lang racketscript/base
(define 0x 42)
```

Compiles to this JavaScript:

```
import * as $rjs_core from '../runtime/core.js';
var 0x = 42;
```

This case occurs in Racket's regular expression library. `collects/racket/private/string` has an identifier named `0-ok?`, and RacketScript seems to choke when working with Racket regular expressions.

**Comment by vishesh** [comment]
@arjunguha Apologies for late response. I'm fixing this along with some other issues I know with identifiers (#36, #7) in this[1] branch. I'm also trying to clean up some code mess which was long due. The first two commit in branch `issue-63` branch should fix this issue. It broke some tests (when compiling with tail-call to loop optimization i.e. when you are not using `--enable-self-tail`) so I'm not merging it for now.

[1] https://github.com/vishesh/racketscript/tree/task/issue-63
