### ISSUE TITLE
Unexpected token `break`

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#67]
When trying to compile waxeye with racketscript, I get:

```
racks/links/srfi-lite-lib/srfi/1/search.rkt.js:1:3274: Unexpected token break
```

The relevant code reads:

```javascript
var break
= function(pred3057, lis3058) {
  return span(function(x3059) {
    return M2.not(pred3057(x3059));
  }, lis3058);
};
```

Looks like racketscript generates `break` as a variable name, but `break` is a keyword in JavaScript and cannot be a variable name.

**Comment by vishesh** [comment]
Correct. Thanks for reporting this. Its about time I fix this!  DUPLICATE #36 

I working on this fix along with some others related issues in this branch: https://github.com/vishesh/racketscript/tree/task/issue-63
