### ISSUE TITLE
Compiling waxeye

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#68]
When compiling https://github.com/orlandohill/waxeye, I get the following error:

```bash
PLTCOLLECTS=":${PWD}/src/racket/" racks -d tmp/racks src/waxeye/waxeye.rkt
```

```
...
[info][assemble] /usr/share/racket/collects/racket/contract/private/arrow-common.rkt
[info][expand] /usr/share/racket/collects/racket/contract/private/guts.rkt
[info][absyn] guts
[info][il] guts
unsupported value0+0.0i
  context...:
   f147
   f150
   /home/glebm/.racket/6.8/pkgs/racketscript-compiler/racketscript/compiler/transform.rkt:566:0: absyn-binding->il
   f182
   [repeats 4 more times]
   /home/glebm/.racket/6.8/pkgs/racketscript-compiler/racketscript/compiler/transform.rkt:211:0: absyn-expr->il
   f182
   [repeats 1 more time]
   /home/glebm/.racket/6.8/pkgs/racketscript-compiler/racketscript/compiler/transform.rkt:211:0: absyn-expr->il
   f182
   /home/glebm/.racket/6.8/pkgs/racketscript-compiler/racketscript/compiler/transform.rkt:211:0: absyn-expr->il
   /home/glebm/.racket/6.8/pkgs/racketscript-compiler/racketscript/compiler/transform.rkt:566:0: absyn-binding->il
   /home/glebm/.racket/6.8/pkgs/racketscript-compiler/racketscript/compiler/transform.rkt:307:7: for-loop
   f182
   f150
   [repeats 1 more time]
```

**Comment by vishesh** [comment]
The Number Pyramid is not yet implemented. This means complex values, big numbers, exact numbers won't work for now. Plan is to port Whalesong/Pyret number library to RacketScript. 

https://github.com/brownplt/pyret-lang/blob/master/src/js/base/js-numbers.js

**Comment by glebm** [comment]
It'd be nice to know what triggers it. As far as I can tell, waxeye is not using any of these numbers.

**Comment by vishesh** [comment]
@glebm From the logs It seems that it is the contract system that is using that. I've not thought much about that part yet.  Is the library using contracts?

**Comment by glebm** [comment]
I don't think so but I am a racket noob. I'd appreciate if you could have a look!

**Comment by vishesh** [comment]
It seems like Waxeye itself is not using contracts, but one of the standard library it uses is using them somewhere which I've not stumbled on. It is possible to build a module dependency graph to trace out. In our compiler its done here[1]. I'll try to do this myself in couple days or so, but if you are willing to you can try it as well.  It will require some some reading on how this module[1][3] (the function involved is `get-export-tree`) and these docs[2][4]. 

[1] https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/compiler/moddeps.rkt
[2] https://docs.racket-lang.org/syntax/module-helpers.html?q=syntax%2Fmoddep#%28mod-path._syntax%2Fmoddep%29
[3] https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/compiler/main.rkt#L398
[4] https://docs.racket-lang.org/graph/index.html

**Comment by glebm** [comment]
I couldn't do the above, but I found at least one contract in a standard library function

Waxeye has:

```racket
(require (only-in racket/format ~r))
```
And the source for that has:
https://github.com/racket/racket/blob/3dd17c73ed59730d5f188f8e93e5e833d19d067c/racket/collects/racket/format.rkt#L63
