### ISSUE TITLE
Use JSDoc

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#78]
This allows us to trivially type-check JS.

It's not as full featured as using actual TypeScript as some types cannot be specified, but it's far better than nothing.

For example:

```bash
npm install -g typescript
tsc --noEmit --allowJs --checkJs --lib es6 --target es6 \
  racketscript-compiler/racketscript/compiler/runtime/core/char.js
```

**Comment by vishesh** [comment]
Cool. I like the idea of being able to statically analyze JS codebase a bit better. This reminds me that I've to make a project wiki or HACKING guide of some kind.

**Comment by glebm** [comment]
OK, closing this.
By the way, it would be even better to drop babel and traceur and just use TypeScript, so that we have types everywhere :)

**Comment by vishesh** [comment]
I think you misunderstood, I said I like the idea of using JSDoc as it allows better static analysis, so we can re-pen this.

I think we can write core run-time in TypeScript pretty easily. For compiler to produce TypeScript, its different story. Racket is a dynamically typed language, and we will not be able to infer much to get exact types. With kernel, there is a possibility if TypeScript can generate contracts for exporting functions to untyped world.

**Comment by glebm** [comment]
> I think we can write core run-time in TypeScript pretty easily. 

Yes, this is what I meant, not producing TypeScript but just using it for the runtime.

**Comment by glebm** [comment]
Closing in favour of #103.
