### ISSUE TITLE
A way to convert a String to UString from RacketScript

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#82]
This is just asking for a manual way to do this (so I can call Waxeye with a `textarea.value`), not the automatic one discussed in #81

**Comment by glebm** [comment]
A concrete syntax proposal:

```racket
($/ustring variable) ;;=> UString.toUString(variable)
```

**Comment by glebm** [comment]
@vishesh Awesome, thanks!

**Comment by vishesh** [comment]
@glebm BTW to make JS style strings you can either do `($/str "Hello")` or `#js"Hello"`. But just found a bug with my Racket 6.10. Will add a fix.
