### ISSUE TITLE
Implement new `hash` kernel primitives

### ISSUE THREAD

**Issue by vishesh** [vishesh/racketscript#91]
6.4 introduced some new primitives:

- [x] `hash-iterate-first`
- [x] `hash-iterate-next`
- [x] `hash-iterate-key`
- [x] `hash-iterate-value`
- [x] `hash-iterate-pair`
- [x] `hash-iterate-key+value`

Also add some other unimplemented hash primitives:

- [ ] `eq-hash-code`
- [ ] `eqv-hash-code`
- [ ] `equal-hash-code`
- [ ] `equal-secondary-hash-code`

**Comment by vishesh** [comment]
@stchang I see you have worked on code around it. Any idea on how `hash-iterate-*` family works in Racket C code? There seems to be two kind of implementation and I think new ones uses these. Any idea on how it works or what data structure it uses? `hash-keys`, `hash-values` are can't work without these.

**Comment by stchang** [comment]
It depends on the hash data structure (Racket has three separate hash implementations) but it's typically just a tree traversal. But since the order doesnt matter, can Racketscript just use the js equivalent for `hash-keys` and `hash-values`?

**Comment by stchang** [comment]
Oh and the `X-hash-code` functions are not for hash tables. They are analogous to Java's `hashCode` method.

**Comment by vishesh** [comment]
@stchang Yeah. I still didn't get chance to look properly into implementation and figure out what is happening. Since its a tree, its not contiguous, and we can't get next item with just an integer without starting from root of tree. I think I need to change implementation of out HAMT library that stores some data at top node to be able to build context and continue without starting over. Or instead of returning int, return an iterator.

**Comment by stchang** [comment]
Yeah, it should be cheaper than a lookup. I remember the Racket implementation returning raw pointer addresses. Let me look into it.

**Comment by glebm** [comment]
@vishesh HAMT does provide a lazy iterator. https://github.com/mattbierner/hamt_plus/blob/b8845c7343fdde3966f875d732248fec597cf538/hamt.js#L859

It's as simple as:

```javascript
const mapIterator = hamtInstance[Symbol.iterator]();
mapIterator.next();
```

**Comment by vishesh** [comment]
@glebm Cool. Thanks for pointing out! Unless we find something fancy in Racket implementation that we don't know about, I think that's the viable solution we have at hand.

**Comment by stchang** [comment]
Commit https://github.com/vishesh/racketscript/commit/3cf780be7823a8e91554cb734c8dcb42983836a9 implements a version of `hash-iterate-X`, without support for mutation while iterating, but enough to run most of the `racket-core` hash tests.

It also adds `prop:equal+hash`, though it looks like `X-hash-code` functions [are previously added here](https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/compiler/runtime/core/hashing.js)?

Can this be closed? Maybe open new issue for mutation during iteration?

**Comment by vishesh** [comment]
SGTM.
