### ISSUE TITLE
Something is up with Structs + hamt

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#95]
If I change `Struct#hashCodeForEqual` to return a constant (e.g. 1), a bunch of tests where structs are put into a hamt fail.

**Comment by vishesh** [comment]
Hey, can you paste the error you get?

**Comment by vishesh** [comment]
`struct/*` didn't fail with this patch for me.

```diff
diff --git a/racketscript-compiler/racketscript/compiler/runtime/core/struct.js b/racketscript-compiler/racketscript/compiler/runtime/core/struct.js
index 89e9980..98157cd 100644
--- a/racketscript-compiler/racketscript/compiler/runtime/core/struct.js
+++ b/racketscript-compiler/racketscript/compiler/runtime/core/struct.js
@@ -137,6 +137,10 @@ class Struct extends Primitive {

        return false;
     }
+
+    hashForEqual() {
+       return 1;
+    }
 }
```

**Comment by glebm** [comment]
Sorry, I've only tried it on my WIP branch and not in `develop` before reporting.
Something else must be going on in that branch.
I'll try to reproduce later once my print/write/display branch passes all tests.
